### ISSUE TITLE
Zentriert und nicht zentriert in der Sidebar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#10]
In der Sidebar wird immer alles zentriert. Das ist aber manchmal nicht gewünscht. Der Text im Beispiel-Screenshot sollte nicht zentriert sein. Das Foto schon. Bei der Überschrift bin ich mir nicht sicher.

![bildschirmfoto 2018-02-22 um 16 08 36](https://user-images.githubusercontent.com/69770/36546088-c20f0eca-17ea-11e8-86ea-75fdb3045e84.png)

**Comment by DerLordi** [comment]
![image](https://user-images.githubusercontent.com/4737847/36551409-cdfe8fdc-17f7-11e8-8287-76e98380d6c2.png)

Hm.. ich finde es tatsächlich zentriert schöner in der sidebar. Hebt sich dann besser vom "main" content ab. Ansonsten, wenn du es anders haben willst, würde ich für die Situationen die Bootstrap Klassen .text-left .text-center und .text-right nehmen und die ans <p> hängen. Dann muss man keine spezial css logik pro Fall schreiben.

**Comment by wintermeyer** [comment]
Du hast Recht.
