### ISSUE TITLE
<ul> in der Sidebar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#11]
Das `<ul>` in der Sidebar wird suboptimal dargestellt. Meiner Meinung nach müsste das wie ein normales `<ul>` mit Punkten und linksbündig dargestellt werden.

![bildschirmfoto 2018-02-22 um 16 10 36](https://user-images.githubusercontent.com/69770/36546160-f634e4ea-17ea-11e8-8972-97dacbe66a43.png)

**Comment by DerLordi** [comment]
https://github.com/wintermeyer/www.reisepassnummer.de/pull/12

**Comment by wintermeyer** [comment]
Irgendwie sieht das "off" aus. @DerLordi: Hast Du eine Ahnung warum?

![bildschirmfoto 2018-02-22 um 22 09 47](https://user-images.githubusercontent.com/69770/36564333-303a7484-181d-11e8-9341-08262e2e1da4.png)

**Comment by DerLordi** [comment]
Ich würde das Bild großer machen, sodass die Ränder mit den Punkten aligned sind. Denke das es dann schöner aussehen sollte. Wenn nicht probiere ich morgen mal rum.

**Comment by wintermeyer** [comment]
Das mit der Bildgröße ist eine sehr gute Idee. Müsste das `<ul>` nicht auch einen Tick mehr nach rechts? Und der Abstand zwischen den `<li>` Zeilen: Müsste der nicht kleiner sein?

**Comment by DerLordi** [comment]
So würde das dann aussehen:

![image](https://user-images.githubusercontent.com/4737847/36584037-6ba33a5a-1878-11e8-8fce-93318a17ea69.png)

**Comment by wintermeyer** [comment]
Sieht IMO besser aus. Wichtig ist nur, das man darunter nicht nur ein `<ul>` sondern auch ein `<p>` oder beides gemischt setzten kann.
