### ISSUE TITLE
Logo für Reisepassnummer.de

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/www.reisepassnummer.de#15]
Es wäre schön, wenn reisepassnummer.de ein schönes Logo haben würde. Damit schafft man Charakter für den Blog, sowie Wiedererkennungswert. Ausserdem würde der Header mobil dann nicht so "leer" aussehen.

Ich habe dir mal ein "Moodboard" zusammengestellt. Kannst du mir sagen, welche Logos dich am meisten ansprechen? Also Stil, Farben, Font usw. 

![image](https://user-images.githubusercontent.com/4737847/36585290-909dda54-187d-11e8-8f95-602c46bd0745.png)

Oder hast du eventuell ganz andere Ideen? 

Ich hatte spontan erstmal an sowas gedacht:
![image](https://user-images.githubusercontent.com/4737847/36585608-daf5e3ca-187e-11e8-9b3c-c7260bfbdd48.png)

Oder sowas, du und deine Familie mit dem Text dazu. Du hälst dabei eine Kamera. Natürlich alles stilisiert und ausgearbeiteter als meine 10sek skizze ^^
![image](https://user-images.githubusercontent.com/4737847/36585668-194fa7dc-187f-11e8-9fc5-5b1edd0e7018.png)

**Comment by wintermeyer** [comment]
Mit dem Logo hast Du Recht.

Gedanken:
- Idealerweise würde es das Reisepass-Thema aufnehmen.
- Es muss auf dem Handy brauchbar aussehen (sprich auch klein funktionieren).
- Es muss auch eine quadratische Variante geben (z.B. für das Podcast).

**Comment by wintermeyer** [comment]
Diese Idee finde ich spannend:
![bildschirmfoto 2018-02-23 um 09 59 40](https://user-images.githubusercontent.com/69770/36585999-4cf6760a-1880-11e8-88d0-28c6951f62fe.png)

Wenn man da noch das Reisepass-Thema bzw. Reise-Stempel reinbringen könnte. Aber das dann auch noch quadratisch umzusetzen?

**Comment by DerLordi** [comment]
Ja, deine Punkte machen Sinn. Ich mach mir mal Gedanken.
