### ISSUE TITLE
Umstellung der / (index-Seite) auf AMP

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#16]
`index.html` auf AMP.

**Comment by DerLordi** [comment]
**Hierzu müssen folgende Dinge erledigt sein: (Liste kann sich ändern und ergänzt werden)**

- [ ] minimum required HTML ist in das Template eingebunden
- [ ] CSS ist inline und an das CSS Boilerplate vom AMP angehangen
- [ ] Jegliches <script> Tag wurde zurückgebaut und eventuell durch amp-variante ersetzt

   - Die sitebar muss eingunden sein
   - Das Audioplayer JS darf nicht mehr geladen werden


_Das sind so meine ersten Gedanken dazu._

**Comment by DerLordi** [comment]
https://validator.ampproject.org/

![image](https://user-images.githubusercontent.com/4737847/37659249-c321e8cc-2c4f-11e8-8a2d-9adcb2986cc7.png)

👍
