### ISSUE TITLE
CSS auf AMP-Konformität abchecken

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#19]
Siehe https://www.ampproject.org/de/docs/guides/responsive/style_pages

Im Zweifelsfall Features rausschmeißen.

**Comment by DerLordi** [comment]
- notice from validator: `CSS syntax error in tag 'style amp-custom' - saw invalid at rule '@-ms-viewport'.` 
- notice from validator: `The inline 'style' attribute is not allowed in AMP documents. Use 'style amp-custom' tag instead.`

**Comment by DerLordi** [comment]
Nur für die Startseite: https://github.com/wintermeyer/www.reisepassnummer.de/pull/35

Alle anderen Seiten müssen noch gecheckt werden auf inline styles etc.

**Comment by DerLordi** [comment]
Hier wurde der Rest gemacht:
PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/37
