### ISSUE TITLE
materialdesignicons.min.css ablösen

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/www.reisepassnummer.de#22]
Die aktuell genutzte Icon Bibliothek ist 15kb groß. Das ist die zweitgrößte lib nach bootstrap (16kb). Dafür das hier nur wenige Icons genutzt werden, kann diese Bibliothek abgelöst und die Icons durch svg Grafiken oder ähnliches ersetzt werden. 

Für AMP darf man das 50kb CSS limit nicht überschreiten.

**Comment by DerLordi** [comment]
Folgende Icons müssen konvertiert werden:

**must-have:** 
- facebook
- twitter
- instagram
- arrow-right
- rss

**nice2have:** (weiß nicht ob wir die noch brauchen, nachdem der audio-player umgezogen ist)
 - play-circle-outline
 - pause-circle-outline
 - skip-backward
 - volume-high
 - download
 - library-music

Diese werde ich im Rahmen dieses Issues in SVG Icons konvertieren. Diese können dann direkt per <svg> Tag ins HTML gerendert werden und benötigen so keine loadtime und sind "blazing fast". 

@wintermeyer Falls dir noch Icons einfallen, welche Sinn machen würden, dann ergänze bitte die Liste.

**Comment by DerLordi** [comment]
Aus Dokumentationsgründen schreib ich einen neuen Kommentar und editiere nicht den anderen.

Die Vorgehensweise mit den SVG Icons ist tatsächlich leider viel zu doof zu handhaben. Ich habe ein wenig recherchiert und anscheinend ist es kein Problem font-awesome mit Hilfe von `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">`einzubinden. 

Das ist eine funktionierende AMP Page mit font-awesome icons:
http://www.enableds.com/products/ampmobile/amp-fonts.php

Deswegen würde ich da den convenience-Weg gehen und hier einfach materiealdesignicons mit font-awesome tauschen. Der Vorteil ist, dass es nicht von unserem CSS-mitgeschickt wird, sondern per cdn geladen wird.

**Comment by wintermeyer** [comment]
Können wir das auch von unserer Domain ausliefern? Das wäre bei HTTP/2 schneller.

**Comment by DerLordi** [comment]
Leider nicht ohne weiteres. Font Awesome musste speziell gewhitelisted werden vom AMP Projekt (https://github.com/ampproject/amphtml/issues/2413). 

Einzige Möglichkeit wäre es Inline in unser CSS zu packen, wobei wir dann aber über das 50kb Limit kommen. Aussee dem wird ein custom Font included was auch wiederum beschränkt ist. 

Vielleicht nutzen wir das jetzt erstmal so, damit die Abhängigkeiten zu den anderen Issues gelöst sind. Ich überlege mir dann zwischendurch wie wir das schöner lösen können. Dürfte ja nicht so schwer sein paar Icons zu bauen. Ich gucke mir dann iwann nochmal die svg Idee an.

**Comment by DerLordi** [comment]
PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/30
