### ISSUE TITLE
CSS mergen und inline rendern

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/www.reisepassnummer.de#25]
Alle CSS files müssen zusammen gemerged werden und inline in jedem File, mit Beachtung der AMP Syntax, ausgegeben werden.

**Comment by wintermeyer** [comment]
Ist es besser das aktuelle CSS zu nehmen oder alles neu aufzusetzen? Ich hänge nicht am aktuellen CSS und auch nicht am aktuellen Layout. Ich will eine Lösung, die möglichst wenig Aufwand bereitet und nicht in den Augen brennt.

**Comment by DerLordi** [comment]
So wie ich es gesehen habe, müsste ich nicht viel am aktuellen CSS machen damit es amp-fähig wird. Deswegen würde ich sagen, dass wir für den ersten Meilenstein noch dieses CSS noch nutzen. 

Danach können wir dann nochmal gucken, ob wir es neu machen, was ein paar Vorteile hätte:

- Wir können Bootstrap durch etwas ersetzen was lightweight ist oder sogar komplett mit CSS grid tauschen
- Wir können sauberes SCSS/SASS schreiben, sodass es leicht ist weitere Features anzubinden

Neu machen würde schon bisschen was an Arbeit bedeuten, deswegen meine ich erst AMP dann schönes CSS.

**Comment by DerLordi** [comment]
Das mit dem "ich muss nicht viel machen" war nicht ganz so richtig. Ich habe eine genaue Beschreibung im Pull Request hinterlassen. Guck dir das bitte mal an und guck ob man das so machen kann. PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/28
