### ISSUE TITLE
Bilder nach build komprimieren

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/www.reisepassnummer.de#29]
Was hälst du von der Idee, dass wir automatisch Bilder beim speichern komprimiert ablegen? Da würde für den Anfang ja ein einfacher imagemagick Befehl reichen:

`convert -strip -interlace Plane -quality 85% input.jpg output.jpg`

Das könnte man automatisch in einem after-save hook über alle  Bilder laufen lassen. 

Ich habe es eben mal mit einem Bild ausprobiert und bin von 287kb auf ~180kb runter ohne sichtbaren Qualitätsverlust. Natürlich könnte man da noch viel mehr aus imagemagick rausholen, wenn man mehr Zeit investiert. 

Oder hast du dazu eine andere Idee?

**Comment by wintermeyer** [comment]
Ist eine gute Idee. Es wäre auch schön, wenn man auf die Bilder klicken könnte, um dann eine große Version zu sehen.

**Comment by DerLordi** [comment]
Ok, dann werde ich mal gucken wie ich das am besten einbauen kann. Schiebe das aber eher nach hinten da es erstmal eher in Richtung nice-to-have tendiert und nicht unbedingt Notwendig für Version 1.0 ist. 

Ja, mit dem vergrößern gebe ich dir Recht. Dazu müsste man dann folgendes bei den Bildern verwenden: https://www.ampproject.org/docs/reference/components/amp-image-lightbox

In dem Zuge kann ich eigentlich auch einbauen, das automatisch thumbnails aus den großen Bildern generiert werden. Das ist mit imagemagick ziemlich einfach zu lösen. 

Dann ändere ich die labels und setzte das als feature.
