### ISSUE TITLE
Sidebar doesn't work in Safari

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#39]
The sidebar in Chrome:
![bildschirmfoto 2018-03-28 um 09 40 18](https://user-images.githubusercontent.com/69770/38015634-a0ce5d00-326c-11e8-9f06-83e7b081870d.png)

Same page in Safari doesn't display a sidebar:
![bildschirmfoto 2018-03-28 um 09 40 11](https://user-images.githubusercontent.com/69770/38015652-adcc0890-326c-11e8-971a-48642aeca121.png)

**Comment by DerLordi** [comment]
Erklärung und PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/44
