### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/www.reisepassnummer.de#4]
Hast du bewusst auf eine mobile Navigation verzichtet? 
Die fehlende Navigation macht es schwer, alles auf der Seite zu finden. So fehlt zum Beispiel auch der Link zum Impressum.

**Comment by wintermeyer** [comment]
Keine Absicht. Eher kein Know-how.

**Comment by DerLordi** [comment]
Ich hätte den Branch fertig. Wenn du mir die Rechte gibst, dann würde ich einen PR erstellen. 
Einziger Diskussionspunkt wäre, dass man jquery einbinden musste um das vorhandene script zu verwenden, welche die mobile nav steuert. 

Das könnte man natürlich umgehen, wenn man das jQuery in vanilla js übersetzt. Wäre natürlich bisschen aufwendiger.

**Comment by wintermeyer** [comment]
Du solltest jetzt write access haben. jQuery ist OK. Die Seite ist eh super langsam. Ich kümmere mich jetzt erst mal um Inhalt. Später kommt Geschwindigkeit.

**Comment by DerLordi** [comment]
https://github.com/wintermeyer/www.reisepassnummer.de/pull/6

Hab dazu einen PR erstellt.

**Comment by wintermeyer** [comment]
Gemerged. Danke!
