### ISSUE TITLE
MP3 player in Safari needs some CSS love

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#40]
The MP3 player in Chrome:

![bildschirmfoto 2018-03-28 um 09 46 17](https://user-images.githubusercontent.com/69770/38015721-f516ed28-326c-11e8-89a0-0b13f6b4166d.png)

Same player in Safari:

![bildschirmfoto 2018-03-28 um 09 46 08](https://user-images.githubusercontent.com/69770/38015727-facdb5da-326c-11e8-8e07-543d068e86f8.png)

**Comment by DerLordi** [comment]
Mit dem PR in welchem ich das grid-model gefixed habe ( ) wird auch die Darstellung des Podcast Players gefixed. Zumindest sieht es bei mir jetzt so aus:

![image](https://user-images.githubusercontent.com/4737847/38437927-4603c45e-39d9-11e8-8643-8665abdca2a7.png)

Die Ansicht die du da gepostet hast, kann ich so nicht nachstellen.
