### ISSUE TITLE
MP3 player doesn't work in Chrome

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#42]
OS:  MacOS X 10.13.3
Browser: Chrome Version 65.0.3325.181 (Offizieller Build) (64-Bit)

The MP3 player stops after one second of playing audio. It works with Safari.

![screenflow](https://user-images.githubusercontent.com/69770/38016050-1e30acac-326e-11e8-8408-543202c24452.gif)

**Comment by wintermeyer** [comment]
In case this is/was an encoding issue: I just exchanged all MP3 in the repository.

**Comment by DerLordi** [comment]
Ist das damit jetzt gefixed? Können wir das Issue schließen?

**Comment by wintermeyer** [comment]
Ja, geht jetzt.
