### ISSUE TITLE
Size of H1 vs H2 vs H3 vs H4

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#43]
The size of the H-Elements is somehow off in the blog posts. It should decrease in size but it doesn't.

**Comment by DerLordi** [comment]
Ich habe die sizes mal angepasst. Insgesamt ein wenig kleiner gemacht. Generell war es schon so, dass die in der Größe absteigend waren. Ausnahme ist der h1.post-title, weil der extra Styles hat. Wenn ich diese ändere, ändern sich alle Überschriften über den posts, auch in der Übersicht. Das sieht dann komisch aus, wenn das so groß ist. Ich denke so sieht es ganz ok aus.
