### ISSUE TITLE
MP3 player im Safari

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#46]
Der MP3 player im Safari sieht nicht so richtig schön aus:
![bildschirmfoto 2018-04-12 um 15 09 59](https://user-images.githubusercontent.com/69770/38679441-0e67ab20-3e64-11e8-99ab-5a491bd8b894.png)

Ist das ein lösbares CSS-Problem oder liegt das an AMP?

Hier der im Chrome:
![bildschirmfoto 2018-04-12 um 15 00 29](https://user-images.githubusercontent.com/69770/38679450-13e2fce4-3e64-11e8-8413-89241dcd761c.png)

**Comment by DerLordi** [comment]
Welche Safari Version verwendest du? 

Meine ist: v 10.1

Bei mir sieht der Player im Safari so aus: 

![image](https://user-images.githubusercontent.com/4737847/38680311-4badb22a-3e66-11e8-8988-ba978ccb1fec.png)

Im Grunde liegt es am Browser wie er das audio Tag darstellt. Der Screenshot von dir sieht aber in der Tat seltsam aus, weil es so aussieht als wolle er ein Video rendern. 

Generell ist es kein AMP Problem, ausser das uns AMP verbietet eine schönere custom Lösung zu bauen, welche in allen Browsern gleich ist.

**Comment by wintermeyer** [comment]
Ich benutze Safari Version 11.1 (13605.1.33.1.2) auf macOS 10.13.4 (17E199). Aber wenn wir eh nichts dran machen können, dann schliesse ich das Issue.
