### ISSUE TITLE
Setup Grayscale CSS

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#48]
https://startbootstrap.com/themes/grayscale/

Please do this with the proper SASS files.

**Comment by wintermeyer** [comment]
"Grayscale is a multipurpose, one page website theme featuring a dark layout along with smooth scrolling page animations."

Just to be sure: I don't want a one page website. I just want the general CSS look and feel. Each podcast or post should have their own page.

**Comment by vidhyav656** [comment]
I have updated the whole website with bootstrap 4.
