### ISSUE TITLE
A new podcast layout

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#49]
Podcast episodes should have their own new layout. With that we should tidy up the structure of those files.

Here is an example of the current YAML configuration for a post:

    ---
    title: 'Everglades - Florida'
    subtitle: 'Mit einem Riesenpropeller im Rücken driften wir durch die Everglades'
    description: 'Mit dem Sumpfboot durch das tropische Marschland. Alligatoren,
    Schildkröten, Vögel und Fische.'
    teaser_text: 'Für 308 US-Dollar driften wir mit einem Airboat durch die Everglades. 90 Kilometer wird hier der langsamste Fluss der Welt breit. Einen Riesenpropeller im Rücken, Ohrstöpsel in den Ohren, begegnen wir am Ufer einem Alligator: „Mathilda“. Ob man hier auch zu Fuß laufen könnte? Ja, sagt unser Begleiter. „Aber…“'
    inserted_at: 2019-05-11 20:24:16 +0100
    updated_at: 2019-06-12 18:25:16 +0100
    categories: Reiseblogger Podcast USA Florida
    hero_image: '/assets/2019/05/11/IMG_1492.jpg'
    hero_image_alt: 'Foto aus dem Airboat'
    layout: default

    podcast_file: '/assets/podcasts/2019-05-11-everglades.mp3'
    podcast_cover: '/assets/podcasts/cover/karl-bewick-1599524-unsplash.jpg'
    podcast_subtitle: 'Everglades - Florida'
    podcast_summary: '👨‍👧‍👦 🐊🇺🇸 Für 308 US-Dollar driften wir mit einem Airboat durch die Everglades. 90 Kilometer wird hier der langsamste Fluss der Welt breit. Einen Riesenpropeller im Rücken, Ohrstöpsel in den Ohren, begegnen wir am Ufer einem Alligator: „Mathilda“. Ob man hier auch zu Fuß laufen könnte? Ja, sagt unser Begleiter. „Aber…“'
    duration: '00:23:40'
    length: '34156086'
    explicit: 'no'
    keywords: 'Podcast, Travelblog, Reisepodcast'
    block: 'no'
    voices: 'Stefan Wintermeyer'
    ---

That is too complex. I'd like to have something like this:

    ---
    title: 'Everglades - Florida'
    subtitle: 'Mit einem Riesenpropeller im Rücken driften wir durch die Everglades'
    description: 'Für 308 US-Dollar driften wir mit einem Airboat durch die Everglades. 90 Kilometer wird hier der langsamste Fluss der Welt breit. Einen Riesenpropeller im Rücken, Ohrstöpsel in den Ohren, begegnen wir am Ufer einem Alligator: „Mathilda“. Ob man hier auch zu Fuß laufen könnte? Ja, sagt unser Begleiter. „Aber…“'
    inserted_at: 2019-05-11 20:24:16 +0100
    updated_at: 2019-06-12 18:25:16 +0100
    categories: Reiseblogger Podcast USA Florida
    hero_image: '/assets/2019/05/11/IMG_1492.jpg'
    hero_image_alt: 'Foto aus dem Airboat'
    hero_image_credit: 'Foto taken by Mr. Smith'
    layout: podcast

    podcast_file: '/assets/podcasts/2019-05-11-everglades.mp3'
    podcast_cover: '/assets/podcasts/cover/karl-bewick-1599524-unsplash.jpg'
    keywords: 'Podcast, Travelblog, Reisepodcast'
    block: 'no'
    voices: 'Stefan Wintermeyer'
    ---

The MP3 data like file size and length should be looked up or calculated by the framework.

**Comment by vidhyav656** [comment]
Using https://podlove.org/podlove-web-player/ to get the episodes from _data/episodes.json and displaying in the individual podcast post
