### ISSUE TITLE
Clean up the top navigation

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#52]
This is the top bar navigation of the old version:

<img width="702" alt="Bildschirmfoto 2019-06-22 um 13 51 21" src="https://user-images.githubusercontent.com/69770/59963557-f089bb00-94f4-11e9-8216-be28e3248fd2.png">

We can tidy it up by just using the following entries:

- Home
- Podcast
- Blog

But we need a link to the `impressum` somewhere on each page. At the bottom would be good.

**Comment by vidhyav656** [comment]
bda41b8001e691006e872ec62da8fe811254c3a1 implemented in this commit
