### ISSUE TITLE
Auto calculate the length and duration of a MP3

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#53]
Please have a look at https://stackoverflow.com/questions/993971/mp3-length-in-milliseconds and implement a way that we don't have to `duration` and `size` manually.

**Comment by wintermeyer** [comment]
```
  "episodes": [
    {
      "duration": "22:08.000",
      "downloads": [
        {
          "assetTitle": "MP3 Audio (mp3)",
          "size": 21315544,
```

**Comment by vidhyav656** [comment]
Even if I get the value dynamically from the above script. I cannot append that value in the `_data/episode.json` file.

**Comment by wintermeyer** [comment]
OK.
