### ISSUE TITLE
Display Instagram photos

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#56]
This part should display the latest photos of https://www.instagram.com/wintermeyer/

<img width="307" alt="Bildschirmfoto 2019-07-07 um 17 23 51" src="https://user-images.githubusercontent.com/69770/60770536-1fe71d00-a0dc-11e9-95c3-8bb6696e25c9.png">

**Comment by vidhyav656** [comment]
Please access this website and [instagram.pixelunion.net](https://instagram.pixelunion.net/) give me the accesstoken of your instagram account. Thank you.

**Comment by wintermeyer** [comment]
Here's the token: 246061780.1677ed0.2c94002be40c4de6b4380328f1f1eb02

**Comment by vidhyav656** [comment]
I need the client id also.

**Comment by vidhyav656** [comment]
[_includes/sidebar.html](https://github.com/wintermeyer/www.reisepassnummer.de/blob/master/jekyll/_includes/sidebar.html) you can give the userId, clientId and accessToken for instagram feeds.

**Comment by wintermeyer** [comment]
But I don't have to change/update anything or do I?

**Comment by vidhyav656** [comment]
It's for future reference or for any changes.
