### ISSUE TITLE
A post without a teaser

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#57]
http://localhost:4000/2018/01/08/neues-layout.html is a post without a teaser photo.

This page shouldn't include an empty imp-tag at all:

<img width="1080" alt="Bildschirmfoto 2019-07-07 um 17 29 05" src="https://user-images.githubusercontent.com/69770/60770583-bb788d80-a0dc-11e9-80e2-77933ed767fe.png">

Same with this:

<img width="301" alt="Bildschirmfoto 2019-07-07 um 17 29 28" src="https://user-images.githubusercontent.com/69770/60770592-cfbc8a80-a0dc-11e9-84bd-805a11004a8d.png">

Same here:

<img width="763" alt="Bildschirmfoto 2019-07-07 um 17 45 59" src="https://user-images.githubusercontent.com/69770/60770787-1dd28d80-a0df-11e9-8eac-c1058cfb0d1c.png">

**Comment by vidhyav656** [comment]
The old version has no cover image https://www.reisepassnummer.de/2018/01/08/neues-layout.html

**Comment by wintermeyer** [comment]
> The old version has no cover image https://www.reisepassnummer.de/2018/01/08/neues-layout.html

That is a blog post. Those don't have cover images. But all the podcasts do.

**Comment by wintermeyer** [comment]
> The old version has no cover image https://www.reisepassnummer.de/2018/01/08/neues-layout.html

Please find an other solution. If there is no image than there shouldn't be an img element in the HTML. Just display nothing. But not a generic "1920 x 1000" image.

**Comment by vidhyav656** [comment]
> > The old version has no cover image https://www.reisepassnummer.de/2018/01/08/neues-layout.html
> 
> Please find an other solution. If there is no image than there shouldn't be an img element in the HTML. Just display nothing. But not a generic "1920 x 1000" image.
Yes.
