### ISSUE TITLE
Point doesn't look quite right

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#60]
This is a small CSS issue. The point is a bit off. It should be located a couple of pixels higher.

<img width="760" alt="Bildschirmfoto 2019-07-07 um 17 57 17" src="https://user-images.githubusercontent.com/69770/60770927-c03f4080-a0e0-11e9-9277-7487339a0013.png">

**Comment by vidhyav656** [comment]
21f615f9b7a785c4df599af828578b0615a6e961
