### ISSUE TITLE
Clean up _data directory

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#63]
There are two files in the `_data/` directory:

- _data/episodes.json
- _data/episodes_new.json

Please delete the one which is not needed.

**Comment by vidhyav656** [comment]
Can you add the /mp3 folder to the root directory of current hosted website.

**Comment by wintermeyer** [comment]
Yes, I can. Just add it to the git repository.

**Comment by vidhyav656** [comment]
https://github.com/wintermeyer/www.reisepassnummer.de/tree/master/jekyll/mp3 please add this.

**Comment by wintermeyer** [comment]
> https://github.com/wintermeyer/www.reisepassnummer.de/tree/master/jekyll/mp3 please add this.

I created the /mp3 directory on the current hosted website. Do you need the content of the master tree too?

**Comment by vidhyav656** [comment]
https://www.reisepassnummer.de/mp3/2018/2018-01-25-queen-victoria.mp3 I wanted this to be the link for the podcast mp3 files in each case.

**Comment by wintermeyer** [comment]
Done.

    ├── 2018
    │   ├── 2018-01-25-queen-victoria.mp3
    │   ├── 2018-02-20-schatzsuche-festung-ehrenbreitstein.mp3
    │   ├── 2018-03-12-zoo-neuwied.mp3
    │   ├── 2018-03-23-breslau.mp3
    │   ├── 2018-04-11-neustadt-an-der-weinstrasse.mp3
    │   ├── 2018-04-16-podcasting-fuer-reiseblogger.mp3
    │   ├── 2018-05-06-minsk.mp3
    │   ├── 2018-05-22-wolfenbuettel.mp3
    │   ├── 2018-07-02-altstadt-barcelona.mp3
    │   └── 2018-11-26-new-providence.mp3
    └── 2019
        ├── 2019-01-23-nightjet.mp3
        ├── 2019-03-08-kapstadt.mp3
        └── 2019-05-11-everglades.mp3

**Comment by vidhyav656** [comment]
thank you.
