### ISSUE TITLE
Missing published date in the MP3 player

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#67]
<img width="979" alt="Bildschirmfoto 2019-07-07 um 19 00 39" src="https://user-images.githubusercontent.com/69770/60771521-9fc7b400-a0e9-11e9-9949-100686b243fd.png">

**Comment by vidhyav656** [comment]
Please check this again. Let me know if its replicate for you.

**Comment by wintermeyer** [comment]
I still have the same problem with Safari:

<img width="408" alt="Bildschirmfoto 2019-07-08 um 17 11 36" src="https://user-images.githubusercontent.com/69770/60821268-808d5d00-a1a3-11e9-9863-28a496bd676a.png">

But I double checked it with Chrome and there it works:

<img width="419" alt="Bildschirmfoto 2019-07-08 um 17 11 29" src="https://user-images.githubusercontent.com/69770/60821289-8c791f00-a1a3-11e9-9717-8a42cf4424a9.png">

In case you have an idea what could be the problem: Please fix it. Otherwise: Feel free to close it.

**Comment by vidhyav656** [comment]
It's working fine on Chrome. Maybe browser compatibility issues with safari.
