### ISSUE TITLE
Links sind nicht als solche erkennbar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/www.reisepassnummer.de#9]
Ein Link ist erst als Link erkennbar, wenn man mit der Maus rüberfährt. Ein Link sollte aber immer als solcher erkennbar sein.

![screenflow](https://user-images.githubusercontent.com/69770/36545851-2b2c73c6-17ea-11e8-912b-b652a8c45321.gif)

**Comment by DerLordi** [comment]
PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/13

**Comment by wintermeyer** [comment]
25a9d490ca544282274cba7452564b5d0d69b0e5

**Comment by wintermeyer** [comment]
hmmm... das sieht bei den Überschriften blöd aus. Kann man das da weg lassen?

![bildschirmfoto 2018-02-22 um 22 12 02](https://user-images.githubusercontent.com/69770/36564412-896f9cbe-181d-11e8-9d40-952fa7ebc226.png)

**Comment by DerLordi** [comment]
Ich hab das "neue" Link styling jetzt auf Links in einem paragraph beschränkt. Nur da gabs erstmal die Probleme das die Links untergehen, soweit ich das überblickt habe.
PR: https://github.com/wintermeyer/www.reisepassnummer.de/pull/14
